Add missing header after 5a30abdf0b3b
../main.c:82:3: error: use of undeclared identifier 'sigset_t'
                sigset_t set;
                ^
../main.c:83:3: error: implicit declaration of function 'sigemptyset' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                sigemptyset(&set);
                ^
../main.c:83:16: error: use of undeclared identifier 'set'
                sigemptyset(&set);
                             ^
../main.c:84:3: error: implicit declaration of function 'sigprocmask' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                sigprocmask(SIG_SETMASK, &set, NULL);
                ^
../main.c:84:15: error: use of undeclared identifier 'SIG_SETMASK'
                sigprocmask(SIG_SETMASK, &set, NULL);
                            ^
../main.c:84:29: error: use of undeclared identifier 'set'
                sigprocmask(SIG_SETMASK, &set, NULL);
                                          ^